### ISSUE TITLE
RPM doesn't require grep-gnu

### ISSUE THREAD

**Issue by ThePrez** [jbh/ibmi-dotfiles#5]
After installing ibmi-dotfiles from RPM, grep fails because it is aliased to `/QOpenSys/pkgs/bin/grep`

That version of grep was not installed as it was not required by the RPM package.

**Comment by jbh** [comment]
Thanks!! I'll look into it.

**Comment by ThePrez** [comment]
There may or may not be a similar issue with `less`

**Comment by ThePrez** [comment]
and `vim`

**Comment by jbh** [comment]
Good catches. I didn't think about those.

**Comment by jbh** [comment]
It should be requiring those now. Please verify.

![image](https://user-images.githubusercontent.com/5510679/51434907-64b3f000-1c31-11e9-8b0c-c003f6230127.png)

**Comment by jbh** [comment]
@ThePrez is this still outstanding?

**Comment by ThePrez** [comment]
No. I think we can close. Thanks!
